DRUM_SEQ_1 = {
    notes: [
        {pitch: 42, quantizedStartStep: 0, quantizedEndStep: 2, isDrum: true},
        {pitch: 42, quantizedStartStep: 2, quantizedEndStep: 4, isDrum: true},
        {pitch: 42, quantizedStartStep: 4, quantizedEndStep: 6, isDrum: true},
        {pitch: 42, quantizedStartStep: 6, quantizedEndStep: 8, isDrum: true},
        {pitch: 42, quantizedStartStep: 8, quantizedEndStep: 10, isDrum: true},
        {pitch: 42, quantizedStartStep: 10, quantizedEndStep: 12, isDrum: true},
        {pitch: 42, quantizedStartStep: 12, quantizedEndStep: 14, isDrum: true},
        {pitch: 42, quantizedStartStep: 14, quantizedEndStep: 16, isDrum: true},

        {pitch: 36, quantizedStartStep: 0, quantizedEndStep: 2, isDrum: true},
        {pitch: 36, quantizedStartStep: 3, quantizedEndStep: 7, isDrum: true},
        {pitch: 36, quantizedStartStep: 5, quantizedEndStep: 6, isDrum: true},
        {pitch: 36, quantizedStartStep: 8, quantizedEndStep: 9, isDrum: true},
        

        {pitch: 38, quantizedStartStep: 4, quantizedEndStep: 6, isDrum: true},
        {pitch: 38, quantizedStartStep: 12, quantizedEndStep: 14, isDrum: true}
      ],
    quantizationInfo: {stepsPerQuarter: 4},
    tempos: [{time: 0, qpm: 70}],
    totalQuantizedSteps: 16
}

DRUM_SEQ_2 = {
  notes: [
      { pitch: 36, isDrum: true, quantizedStartStep: 0, quantizedEndStep: 1 },
      { pitch: 46, isDrum: true, quantizedStartStep: 0, quantizedEndStep: 1 },
      { pitch: 36, isDrum: true, quantizedStartStep: 3, quantizedEndStep: 4 },
      { pitch: 38, isDrum: true, quantizedStartStep: 4, quantizedEndStep: 5 },
      { pitch: 46, isDrum: true, quantizedStartStep: 4, quantizedEndStep: 5 },
      { pitch: 36, isDrum: true, quantizedStartStep: 7, quantizedEndStep: 8 },
      { pitch: 36, isDrum: true, quantizedStartStep: 8, quantizedEndStep: 9 },
      { pitch: 46, isDrum: true, quantizedStartStep: 8, quantizedEndStep: 9 },
      { pitch: 36, isDrum: true, quantizedStartStep: 11, quantizedEndStep: 12 },
      { pitch: 38, isDrum: true, quantizedStartStep: 12, quantizedEndStep: 13 },
      { pitch: 46, isDrum: true, quantizedStartStep: 12, quantizedEndStep: 13 },
      { pitch: 36, isDrum: true, quantizedStartStep: 15, quantizedEndStep: 16 },
      { pitch: 36, isDrum: true, quantizedStartStep: 16, quantizedEndStep: 17 },
      { pitch: 46, isDrum: true, quantizedStartStep: 16, quantizedEndStep: 17 },
      { pitch: 36, isDrum: true, quantizedStartStep: 19, quantizedEndStep: 20 },
      { pitch: 38, isDrum: true, quantizedStartStep: 20, quantizedEndStep: 21 },
      { pitch: 46, isDrum: true, quantizedStartStep: 20, quantizedEndStep: 21 },
      { pitch: 36, isDrum: true, quantizedStartStep: 23, quantizedEndStep: 24 },
      { pitch: 36, isDrum: true, quantizedStartStep: 24, quantizedEndStep: 25 },
      { pitch: 46, isDrum: true, quantizedStartStep: 24, quantizedEndStep: 25 },
      { pitch: 36, isDrum: true, quantizedStartStep: 27, quantizedEndStep: 28 },
      { pitch: 38, isDrum: true, quantizedStartStep: 28, quantizedEndStep: 29 },
      { pitch: 46, isDrum: true, quantizedStartStep: 28, quantizedEndStep: 29 },
      { pitch: 36, isDrum: true, quantizedStartStep: 31, quantizedEndStep: 32 },
      { pitch: 36, isDrum: true, quantizedStartStep: 32, quantizedEndStep: 33 },
      { pitch: 46, isDrum: true, quantizedStartStep: 32, quantizedEndStep: 33 },
      { pitch: 36, isDrum: true, quantizedStartStep: 35, quantizedEndStep: 36 },
      { pitch: 38, isDrum: true, quantizedStartStep: 36, quantizedEndStep: 37 },
      { pitch: 46, isDrum: true, quantizedStartStep: 36, quantizedEndStep: 37 },
      { pitch: 36, isDrum: true, quantizedStartStep: 39, quantizedEndStep: 40 },
      { pitch: 36, isDrum: true, quantizedStartStep: 40, quantizedEndStep: 41 },
      { pitch: 46, isDrum: true, quantizedStartStep: 40, quantizedEndStep: 41 },
      { pitch: 36, isDrum: true, quantizedStartStep: 43, quantizedEndStep: 44 },
      { pitch: 38, isDrum: true, quantizedStartStep: 44, quantizedEndStep: 45 },
      { pitch: 46, isDrum: true, quantizedStartStep: 44, quantizedEndStep: 45 },
      { pitch: 36, isDrum: true, quantizedStartStep: 47, quantizedEndStep: 48 },
      { pitch: 36, isDrum: true, quantizedStartStep: 48, quantizedEndStep: 49 },
      { pitch: 46, isDrum: true, quantizedStartStep: 48, quantizedEndStep: 49 },
      { pitch: 36, isDrum: true, quantizedStartStep: 51, quantizedEndStep: 52 },
      { pitch: 38, isDrum: true, quantizedStartStep: 52, quantizedEndStep: 53 },
      { pitch: 46, isDrum: true, quantizedStartStep: 52, quantizedEndStep: 53 },
      { pitch: 36, isDrum: true, quantizedStartStep: 55, quantizedEndStep: 56 },
      { pitch: 36, isDrum: true, quantizedStartStep: 56, quantizedEndStep: 57 },
      { pitch: 46, isDrum: true, quantizedStartStep: 56, quantizedEndStep: 57 },
      { pitch: 36, isDrum: true, quantizedStartStep: 59, quantizedEndStep: 60 },
      { pitch: 38, isDrum: true, quantizedStartStep: 60, quantizedEndStep: 61 },
      { pitch: 46, isDrum: true, quantizedStartStep: 60, quantizedEndStep: 61 },
      { pitch: 36, isDrum: true, quantizedStartStep: 63, quantizedEndStep: 64 }
  ],
  quantizationInfo: {
      stepsPerQuarter: 4
  },
  totalQuantizedSteps: 64
}

DRUM_SEQ_3 = {
  notes: [
      { pitch: 36, isDrum: true, quantizedStartStep: 0, quantizedEndStep: 1 },
      { pitch: 49, isDrum: true, quantizedStartStep: 0, quantizedEndStep: 1 },
      { pitch: 46, isDrum: true, quantizedStartStep: 4, quantizedEndStep: 5 },
      { pitch: 38, isDrum: true, quantizedStartStep: 8, quantizedEndStep: 9 },
      { pitch: 46, isDrum: true, quantizedStartStep: 8, quantizedEndStep: 9 },
      { pitch: 46, isDrum: true, quantizedStartStep: 12, quantizedEndStep: 13 },
      { pitch: 36, isDrum: true, quantizedStartStep: 16, quantizedEndStep: 17 },
      { pitch: 46, isDrum: true, quantizedStartStep: 16, quantizedEndStep: 17 },
      { pitch: 46, isDrum: true, quantizedStartStep: 20, quantizedEndStep: 21 },
      { pitch: 38, isDrum: true, quantizedStartStep: 24, quantizedEndStep: 25 },
      { pitch: 46, isDrum: true, quantizedStartStep: 24, quantizedEndStep: 25 },
      { pitch: 46, isDrum: true, quantizedStartStep: 28, quantizedEndStep: 29 },
      { pitch: 36, isDrum: true, quantizedStartStep: 32, quantizedEndStep: 33 },
      { pitch: 46, isDrum: true, quantizedStartStep: 32, quantizedEndStep: 33 },
      { pitch: 46, isDrum: true, quantizedStartStep: 36, quantizedEndStep: 37 },
      { pitch: 38, isDrum: true, quantizedStartStep: 40, quantizedEndStep: 41 },
      { pitch: 46, isDrum: true, quantizedStartStep: 40, quantizedEndStep: 41 },
      { pitch: 46, isDrum: true, quantizedStartStep: 44, quantizedEndStep: 45 },
      { pitch: 36, isDrum: true, quantizedStartStep: 48, quantizedEndStep: 49 },
      { pitch: 46, isDrum: true, quantizedStartStep: 48, quantizedEndStep: 49 },
      { pitch: 46, isDrum: true, quantizedStartStep: 52, quantizedEndStep: 53 },
      { pitch: 38, isDrum: true, quantizedStartStep: 56, quantizedEndStep: 57 },
      { pitch: 46, isDrum: true, quantizedStartStep: 56, quantizedEndStep: 57 },
      { pitch: 46, isDrum: true, quantizedStartStep: 60, quantizedEndStep: 61 }
  ],
  quantizationInfo: {
      stepsPerQuarter: 4
  },
  totalQuantizedSteps: 64
}

DRUM_SEQ_4 = {
  notes: [
      { pitch: 36, isDrum: true, quantizedStartStep: 0, quantizedEndStep: 1 },
      { pitch: 42, isDrum: true, quantizedStartStep: 0, quantizedEndStep: 1 },
      { pitch: 36, isDrum: true, quantizedStartStep: 2, quantizedEndStep: 3 },
      { pitch: 42, isDrum: true, quantizedStartStep: 2, quantizedEndStep: 3 },
      { pitch: 38, isDrum: true, quantizedStartStep: 4, quantizedEndStep: 5 },
      { pitch: 42, isDrum: true, quantizedStartStep: 4, quantizedEndStep: 5 },
      { pitch: 42, isDrum: true, quantizedStartStep: 6, quantizedEndStep: 7 },
      { pitch: 36, isDrum: true, quantizedStartStep: 7, quantizedEndStep: 8 },
      { pitch: 36, isDrum: true, quantizedStartStep: 8, quantizedEndStep: 9 },
      { pitch: 42, isDrum: true, quantizedStartStep: 8, quantizedEndStep: 9 },
      { pitch: 36, isDrum: true, quantizedStartStep: 10, quantizedEndStep: 11 },
      { pitch: 42, isDrum: true, quantizedStartStep: 10, quantizedEndStep: 11 },
      { pitch: 38, isDrum: true, quantizedStartStep: 12, quantizedEndStep: 13 },
      { pitch: 42, isDrum: true, quantizedStartStep: 12, quantizedEndStep: 13 },
      { pitch: 42, isDrum: true, quantizedStartStep: 14, quantizedEndStep: 15 },
      { pitch: 36, isDrum: true, quantizedStartStep: 16, quantizedEndStep: 17 },
      { pitch: 42, isDrum: true, quantizedStartStep: 16, quantizedEndStep: 17 },
      { pitch: 36, isDrum: true, quantizedStartStep: 18, quantizedEndStep: 19 },
      { pitch: 42, isDrum: true, quantizedStartStep: 18, quantizedEndStep: 19 },
      { pitch: 38, isDrum: true, quantizedStartStep: 20, quantizedEndStep: 21 },
      { pitch: 42, isDrum: true, quantizedStartStep: 20, quantizedEndStep: 21 },
      { pitch: 42, isDrum: true, quantizedStartStep: 22, quantizedEndStep: 23 },
      { pitch: 36, isDrum: true, quantizedStartStep: 23, quantizedEndStep: 24 },
      { pitch: 36, isDrum: true, quantizedStartStep: 24, quantizedEndStep: 25 },
      { pitch: 42, isDrum: true, quantizedStartStep: 24, quantizedEndStep: 25 },
      { pitch: 36, isDrum: true, quantizedStartStep: 26, quantizedEndStep: 27 },
      { pitch: 42, isDrum: true, quantizedStartStep: 26, quantizedEndStep: 27 },
      { pitch: 38, isDrum: true, quantizedStartStep: 28, quantizedEndStep: 29 },
      { pitch: 42, isDrum: true, quantizedStartStep: 28, quantizedEndStep: 29 },
      { pitch: 42, isDrum: true, quantizedStartStep: 30, quantizedEndStep: 31 },
      { pitch: 36, isDrum: true, quantizedStartStep: 32, quantizedEndStep: 33 },
      { pitch: 42, isDrum: true, quantizedStartStep: 32, quantizedEndStep: 33 },
      { pitch: 36, isDrum: true, quantizedStartStep: 34, quantizedEndStep: 35 },
      { pitch: 42, isDrum: true, quantizedStartStep: 34, quantizedEndStep: 35 },
      { pitch: 38, isDrum: true, quantizedStartStep: 36, quantizedEndStep: 37 },
      { pitch: 42, isDrum: true, quantizedStartStep: 36, quantizedEndStep: 37 },
      { pitch: 42, isDrum: true, quantizedStartStep: 38, quantizedEndStep: 39 },
      { pitch: 36, isDrum: true, quantizedStartStep: 39, quantizedEndStep: 40 },
      { pitch: 36, isDrum: true, quantizedStartStep: 40, quantizedEndStep: 41 },
      { pitch: 42, isDrum: true, quantizedStartStep: 40, quantizedEndStep: 41 },
      { pitch: 36, isDrum: true, quantizedStartStep: 42, quantizedEndStep: 43 },
      { pitch: 42, isDrum: true, quantizedStartStep: 42, quantizedEndStep: 43 },
      { pitch: 38, isDrum: true, quantizedStartStep: 44, quantizedEndStep: 45 },
      { pitch: 42, isDrum: true, quantizedStartStep: 44, quantizedEndStep: 45 },
      { pitch: 42, isDrum: true, quantizedStartStep: 46, quantizedEndStep: 47 },
      { pitch: 36, isDrum: true, quantizedStartStep: 48, quantizedEndStep: 49 },
      { pitch: 42, isDrum: true, quantizedStartStep: 48, quantizedEndStep: 49 },
      { pitch: 36, isDrum: true, quantizedStartStep: 50, quantizedEndStep: 51 },
      { pitch: 42, isDrum: true, quantizedStartStep: 50, quantizedEndStep: 51 },
      { pitch: 38, isDrum: true, quantizedStartStep: 52, quantizedEndStep: 53 },
      { pitch: 42, isDrum: true, quantizedStartStep: 52, quantizedEndStep: 53 },
      { pitch: 42, isDrum: true, quantizedStartStep: 54, quantizedEndStep: 55 },
      { pitch: 36, isDrum: true, quantizedStartStep: 55, quantizedEndStep: 56 },
      { pitch: 36, isDrum: true, quantizedStartStep: 56, quantizedEndStep: 57 },
      { pitch: 42, isDrum: true, quantizedStartStep: 56, quantizedEndStep: 57 },
      { pitch: 36, isDrum: true, quantizedStartStep: 58, quantizedEndStep: 59 },
      { pitch: 42, isDrum: true, quantizedStartStep: 58, quantizedEndStep: 59 },
      { pitch: 38, isDrum: true, quantizedStartStep: 60, quantizedEndStep: 61 },
      { pitch: 42, isDrum: true, quantizedStartStep: 60, quantizedEndStep: 61 },
      { pitch: 42, isDrum: true, quantizedStartStep: 62, quantizedEndStep: 63 }
  ],
  quantizationInfo: {
      stepsPerQuarter: 4
  },
  totalQuantizedSteps: 64
}